# wrangler.toml
name = "github-file-api"
main = "src/index.js"
compatibility_date = "2024-03-15" # 请使用一个较新的日期

# -- Variables (non-secret, accessible via env.VAR_NAME) --
[vars]
GITHUB_REPO_OWNER = "bobfile666"  # 替换为你的
GITHUB_REPO_NAME = "bob-files"      # 替换为你的
TARGET_BRANCH = "main"
LOGGING_ENABLED = "true"
# API_VERSION = "v1" # 可选

# -- KV Namespaces --
[[kv_namespaces]]
binding = "USER_UPLOAD_TIMESTAMPS_KV" # 这是你在代码中访问 KV 的方式：env.USER_UPLOAD_TIMESTAMPS_KV
id = "28e4a81a53434f688795f3d3b4812f9b" # 粘贴你从 Dashboard 获取的 KV Namespace ID
# preview_id = "YOUR_KV_NAMESPACE_PREVIEW_ID_HERE" # (可选) 如果你有单独的预览 Namespace ID

# -- D1 Databases --
[[d1_databases]]
binding = "DB" # 这是你在代码中访问 D1 的方式：env.DB
database_name = "github-file-api-db" # 你在 Dashboard 中创建的 D1 数据库名
database_id = "07be31d3-dda3-4473-9f79-f749ad54b8cf" # 粘贴你从 Dashboard 获取的 D1 Database ID
# preview_database_id = "YOUR_D1_PREVIEW_DATABASE_ID_HERE" # (可选)

# -- Secrets (set these in Cloudflare Dashboard) --
# 不要将实际的 secret 值写在这里。这些只是占位符，提醒你需要设置它们。
# GITHUB_PAT
# DYNAMIC_TOKEN_SECRET
# MASTER_ENCRYPTION_KEY

# 新增：Cron Triggers
# "*/5 * * * *"  每 5 分钟
# "0 */2 * * *"  每 2 小时的第 0 分钟运行 (00:00, 02:00, 04:00, etc.)
[triggers]
crons = ["0 */2 * * *"]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



